---
title: ""
output: pdf_document
---


## Ecological surveys
***

#### Survey methods

Fish surveys were point counts of 7 m radius (Seychelles) or belt transects of 50 m length (Maldives, Chagos, GBR) conducted on hard-bottom reef habitat at 8-10 m depth. Surveys were designed to minimize diver avoidance or attraction. In point counts, large mobile species were censused before smaller reef-dwelling species. In belt transects, large mobile fish were surveyed in one direction for a 5 m transect width, and small site-attached species were recorded in the opposite direction for a 2 m transect width. For both survey types, all diurnal, non-crypic (>8cm) reef-associated fish were counted and sized to the nearest centimetre (total length, TL). TL measurements were calibrated by estimating the length of sections of PVC pipe and comparing it to their known length prior to data collection each day. All fish sizes (total length, cm) were then converted to body mass (grams) using published length ~ weight relationships (Froese & Pauly 2017), and standardized by survey area to give species-level biomass estimates that were comparable across datasets (kg hectare^-1^). 

<br><br>

Following fish surveys, benthic habitat composition was surveyed with 50 m line transects. Benthos composition was recorded by identifying the benthic taxa directly under the transect line at 50 cm intervals. Taxa were grouped into broad functional groups (e.g. CCA, macroalgae, turf algae) and, if they were hard corals, identified to genus level. The structural complexity of the reef was visually estimated on a six-point scale, ranging from 0 (no vertical relief) to 5 (complex habitat with caves and overhangs) [@Polunin1993], which correlates strongly with a range of other methods for capturing the structural complexity of coral reefs [@Wilson2007]. Observation error and bias were minimized because one observer (NAJG) performed all surveys, except for benthic surveys in Seychelles (SW). Although we combined two UVC methods to estimate fish biomass, point counts and belt transects give comparable biomass estimates [@Samoilys2000].

#### Region details [put in supplementary?]

In Seychelles, 21 reefs were surveyed in 2008, 2014, and 2017 on two inhabited islands (Mahe, Praslin) (REF relevant Graham paper here). Surveys were conducted on the reef slope at 9-12m depth, and stratified to include carbonate fringing reefs, granitic rocky reefs with coral growth, and patch reef habitats on a sand, rubble, or rock base (Fig MAP). Surveys were repeated for either 8 (2008) or 16 (2011, 2014, 2017) replicates at each reef, which were located at least 15m away from each other. To ensure that survey effort was comparable among Seychelles reefs, we only considered surveys from the first 8 replicates (per site per survey year).  Overall, the surveys covered up to 0.5km of reef front and 2,500m^2^ of reef habitat, including 672 point counts over 4 surveyed years. Reefs were categorised by their exploitation status, with 9 sites in small protected areas and 12 sites supporting artisanal fisheries.

<br><br>

In Australia, five reefs were surveyed on the central Great Barrier Reef in 2010 and 2011 (Wheeler, Davies, Rib, Trunk, John Brewer) [@Graham2011]. Reefs were stratified to include 3 wave exposed and 3 wave sheltered locations (6 per reef), which were further divided into reef slope (7-9m depth), reef crest (2-3m depth), and reef flat (100m distance from crest). Each location and habitat type was surveyed with four replicate transects. We used data for surveys conducted on the reef slope, which produced a dataset of 24 transects per reef and 120 transects in total. All reefs were categorised as protected from fishing, as herbivore species are not commonly targeted by GBR fisheries [@Graham2011].

<!... is it reasonable to include crest and flat locations? Other regions are reef slope. Also a depth issue. ...>

<!... You're right, I don't think it's reasonable - should talk about that in the next meeting. ...>


<br><br>

In Chagos archipelago, 25 reefs were surveyed on four uninhabited atolls in 2010 (Fig MAP). Surveys were stratified to include sheltered (9) and exposed (9) habitats, and four replicate transects were conducted at each site, resulting in 100 total transects. All reefs were categorised as pristine.

<!... Need wave exposure details for Diego Garcia and Peros Banhos ...>

In Maldives, 11 reefs were surveyed on one atoll (Huvadhoo) in 2013. Surveys were conducted on the reef slope for 4 replicates per reef, resulting in 44 total transects.

#### Herbivore feeding observations

Feeding observations of Indo-Pacific herbivores provided species-level estimates on bite rates and, for scrapers, bite volumes. Surveys were conducted in the Red Sea (AH), Indonesia (AH), and GBR (AH and AGL). We only analysed feeding observations for species observed in the UVC dataset (39). For each observed fish, we estimated the average feeding rate (bites per minute). For scrapers, we also estimated the average bite scar size. We define an individuals' functional impact by its feeding intensity (bite rate) but, by using in situ feeding observations that track fish forays, our approach accounts for variation in feeding frequency (the timing and distance of feeding forays) (Nash et al. 2013). 

#### Ecological variable processing

Herbivore species were categorised as croppers, scrapers and excavators, or browsers according to published diet observations (Froese & Pauly 2017) and observations of feeding behaviours [@Green2009]. Croppers were defined as species feeding primarily on turf algae (REF), scraper and excavator species fed primarily on exposed coral substrate (REF), and browsers fed primarily on established macroalgae (REF) (Table S1). Fish biomass estimates were averaged across replicates at each site to give the total biomass (kg ha^-1^) of each functional feeding group (grazers, scrapers, browsers), and these estimates formed the basis of all subsequent analyses.

<!... Croppers replacing grazers needs to be mentioned ealier ...>

We defined grazing functions separately for each functional group, and used feeding observations to convert UVC observations into the total grazing potential of croppers, scrapers, and browsers. We used a Bayesian hierarchical modelling framework that estimate species- and genera-level functional rates, which allowed us to estimate grazing for UVC species which were not observed in feeding surveys (63). Cropper function was quantified in terms of potential feeding intensity, measured as the total number of bites per minute and derived from a predictive model which accounted for species- and genera-specific bite rates:

$bite_rate = Gamma(\mu, \theta)$
$log(\mu) = X + species_i + genus_j$

We estimated the grazing rate of each cropper observed in UVCs, and used allometric relationships to convert bite rates into grams of carbon removed through EAM consumption [@Marshell2015]. From Van Rooij et al. [@VanRooij1998], daily carbon intake was linked to body mass as

$grams carbon = 0.0342 * body mass^0.816$

which we then divided by the predicted number of bites per day to produce an estimate of grams carbon consumed per minute by each cropper fish observed in UVCs. We summed estimates within each UVC survey and averaged across surveys to give site-level estimates of potential cropping function.

For scrapers and excavators, we defined the potential scraping function in terms of area of substrate removed per hour. Feeding observations provided estimates of bite rates and average scar sizes (scar_area), which we modelled with species- and genera-specific grazing rates.

$bite = Gamma(\mu, \theta)$
$log(\mu) = X + B*TL + species_i + genus_j$

$scar_area = Gamma(\mu, \theta)$
$log(\mu) = X + B*TL + species_i + genus_j$

$area_removed = Normal(\mu, \sigma)$
$\mu = X + ??$

By including size (TL) as an explanatory covariate, our model accounted for body size effects, as scar sizes increased with body size (Fig. SX) and bite rates decreased with body size (Fig. SX). UVC observations were converted to area removed per minute, summed within surveys, and averaged to give site-level estimates of potential scraping function.

Browsing function was quantified in terms of mass standardized bites, thereby quantifying the potential grazing impact of browsers in removing macroalgal material [@Verges2012]. Feeding observations provided estimates of bite rates for two genera, which we fitted as random effects:

$bite = Normal(\mu, \sigma)$
$\mu = X + genus_j$

Using predictions for species, genera, or average browser bite rates, we converted UVC browser observations into a mass standardized bite rate (bites *x* kg), summed browser grazing impact per survey, and averaged estimates to produce site-level estimates of browser function. 

Explanatory covariates were derived from fish and benthic surveys. First, to account for fishing effects ranging from pristine Chagos reefs to heavily-exploited Seychelles reefs, we estimated total community biomass as a proxy for exploitation pressure. Fishable biomass is highly sensitive to exploitation pressure and, in the Indian Ocean, is predicted by human populations, access to markets, and fisheries management [@McClanahan2016]. Reefs were also assigned a categorical fishing pressure covariate to distinguish between protected, exploited, and pristine reefs. Second, benthic surveys provided site-level estimates of benthic composition. We estimated the site-level cover for four major habitat-forming groups (live hard coral, macroalgae, sand, and rubblerubble), and structural complexity, by averaging across replicates at each site. To understand the range of benthic habitat types across the dataset, we conducted a PCA to identify common habitat groupings (i.e. benthic regimes) [@Jouffray2015]. Prior to statistical modelling, we scaled and centered all continuous covariates to a mean of zero and standard deviation of one, and converted the categorical protection covariate into two dummy variables (fished - protected, fished - pristine) [@Schielzeth2010].

## Statistical analyses
***

We used linear mixed effects to model to examine variation in herbivore biomass and functional impact along gradients in benthic habitat composition and fishing intensity. Benthic fixed effects were hard coral, macroalgae, sand, rubble and structural complexity, and fishing fixed effects were fishable biomass and fishing protection (pristine/fished and fished/protected). Potential covariance among reefs in the same dataset and year was modelled using random intercept terms. Models were fitted separately for each functional feeding group for normally distributed errors with biomass log_10_ transformed:

$biomass_{ijk} = A + B*hardcoral_{ijk} + C*macroalgae_{ijk} + D*sand_{ijk} + E*rubble_{ijk} + F*complexity_{ijk} + G*fishablebiomass_{ijk} + H*pristine.fished_{ijk} + I*fished.protected_{ijk} + year_j + dataset_k + \epsilon_{ijk}$

Parameter estimates were extracted to compare effect sizes of each explanatory covariate, and fitted relationships were visualized with model predictions that excluded random effects. Model diagnostics were assessed for normality using residual plots. 

Finally, we estimated the potential decoupling of biomass from function by fitting a linear mixed effects model of biomass ~ function for each functional group, with random intercepts for dataset. We ensured that our decoupling analysis was robust to missing bite rate data by refitting biomass ~ function models after subsetting the biomass data to species observed in feeding observations.
