---
title: ""
output: pdf_document
---


## Grazer and benthic survey methods

#### Seychelles

#### GBR
The ecological assessment of the GBR was done between November 2010 and January 2011. Five mid-shelf reefs near the city of Townsville were surveyed by splitting them into 3 wave exposed and 3 wave sheltered sites. Each of these 6 sites were split up again along a zonal gradient into 3 zones - crest (2-3m depth), slope (7-9m depth), and flat (100m distance from crest). Each zone was surveyed with 4 50m-transects. The experimental setup yielded in 72 transects per reef and 360 for all 5 reefs combined.

Each 50m-transect recorded 3 parts of the environment.
1.) Fish surveys focused on diurnally active, non-cryptic, reef-associated fish species above a total length (TL) of 8cm. As the transect was layed out, larger individual fish were recorded within a 5x50m belt transect. On the return pass, the belt's width was reduced to 2m and small territorial species were recorded. Every individual fish was recorded with abundance, its TL to the nearest cm and identified to species level. 
2.) Structural complexity was estimated visually on a 6-point-scale, from 0 (no vertical relief) to 5 (complex habitat with caves and overhangs), (Polunin & Roberts 1993) and  recorded for each transect.
3.) Benthos composition was recorded by noting the benthic taxa directly under the 50m-line every 50 cm. Taxa were either grouped into broader functional groups (e.g. CCA, macroalgae, turf algae) or, if they were hard corals, identified to genus level and the growth form was also recorded. 

#### Chagos & Maldives

  In Maldives and Chagos, ecological surveys were conducted using belt transects on hard-bottom reef habitat at 8-10m depth. In each transect, one observer recorded the abundance, size and identify of all diurnal reef-associated fishes >8 cm. Large mobile fishes were surveyd in 5 x 50 m transects and small site-attached species were recorded with  2 x 50m transects. For each transect size, 4 replicate transects were conducted at each site along the 3m and 9m depth contour. 

Following fish surveys, benthic community composition was surveyed with 4 x 50 m line transects. The benthic taxa (hard coral genera, macroalgae, etc., etc.) direclty below the transect was recorded at each 50 cm. Data were converted to percent cover for each transect. Habitat complexity was assessed on a 6-point scal (Polunin & Roberts 1993) ranging from 0 (no vertical relief) to 5 (complex habitat with caves and overhangs).

Chagos surveys encompassed 25 sites on 4 atolls and were conducted in 2010, Maldives surveys encompassed 11 sites on 1 atoll and were conducted in 2013.

#### General data treatment stuff

Observation error and bias were minimized because one observer (NAJ) performed all surveys, except for benthic surveys in Seychelles (Shaun Wilson).

All fish sizes (total length, cm) were converted to body mass (grams) using published length ~ weight relationships, and standardized by transect area as kg per hectare.

Fish biomass estimates were averaged across transects at each site, for each functional feeding group.
