---
title: "Models 1 - Herbivore biomass gradients"
output:
  pdf_document: default
  html_notebook: default
  html_document:
    df_print: paged
---

#### Report contains model outputs and diagnostics for grazing biomass models.

```{r, echo=FALSE, include=FALSE, messages=FALSE}

# package loads
library(ggplot2); library(visreg); library(lme4); library(dplyr); library(tidyr)
theme_set(theme_bw())

# data load
load("../../data/wio_herb_benthic_merged.Rdata")

# estimate mean biomass per site per FG
h <- pred %>% 
  ## sum biomass per FG in each transect
        group_by(dataset, date, reef, site, management, transect, 
                 unique.id, depth, FG,
                         hard.coral, macroalgae, complexity) %>%
          summarise(biom = sum(biomass.kgha)) %>%
  ## mean FG biomass across transects at each site
          group_by(dataset, date, reef, site, management, unique.id, depth, FG,
                         hard.coral, macroalgae, complexity) %>%
          summarise(biom = mean(biom)) 


#ggplot(h, aes(x = hard.coral, y = biom, col=FG)) + geom_point()
#ggplot(h, aes(management, log10(biom+1), fill=FG)) + geom_boxplot()
#hist(h$biom[h$FG == 'Herbivore Scraper'])


h<- spread(h, FG, biom, fill=0)
colnames(h)[11:13]<-c('browser', 'grazer', 'scraper')
h<-as.data.frame(h)

#cor(h$hard.coral, h$complexity)
#cor(h$hard.coral, h$macroalgae)

```

```{r, echo=FALSE, include=TRUE, messages=FALSE, fig.cap='Correlation between explanatory covariates', fig.height=10, fig.width=10}
source('../../scripts/functions/plot-cor-functions.R')
pairs2(data.frame(h$hard.coral, h$macroalgae, h$complexity, h$management), 
       lower.panel=panel.smooth2, upper.panel = panel.cor)
```

```{r, echo=FALSE, include=FALSE, messages=FALSE}

##scale vars
h$hard.coral <- scale(h$hard.coral)
h$macroalgae <- scale(h$macroalgae)
h$complexity <- scale(h$complexity)

## convert biomass to log10
h$grazerlog10<-log10(h$grazer+1)
h$scraperlog10<-log10(h$scraper+1)
h$browserlog10<-log10(h$browser+1)

# testing model fit
m<-lmer(grazerlog10 ~ hard.coral + macroalgae * complexity + management + ## fixed
          (1 | dataset/reef) , ## random, nested = reefs within datasets
                data = h)
summary(m)
```

\newpage
### Grazers

```{r, echo=FALSE, include=FALSE, messages=FALSE}
#### GRAZER BIOMASS MODELS

```