---
title: "Models 1 - Herbivore biomass gradients"
output:
  pdf_document: default
  html_notebook: default
  html_document:
    df_print: paged
---

#### Report contains model outputs and diagnostics for grazing biomass models.

```{r, echo=FALSE, include=FALSE, messages=FALSE}

# package loads
library(ggplot2); library(visreg); library(lme4); library(dplyr); library(tidyr)
theme_set(theme_bw())

# data load
load("../../data/wio_herb_benthic_merged.Rdata")

# estimate mean biomass per site per FG
h <- pred %>% 
  ## sum biomass per FG in each transect
        group_by(dataset, date, reef, site, management, transect, 
                 unique.id, depth, FG,
                         hard.coral, macroalgae, complexity) %>%
          summarise(biom = sum(biomass.kgha)) %>%
  ## mean FG biomass across transects at each site
          group_by(dataset, date, reef, site, management, unique.id, depth, FG,
                         hard.coral, macroalgae, complexity) %>%
          summarise(biom = mean(biom)) 


#ggplot(h, aes(x = hard.coral, y = biom, col=FG)) + geom_point()
#ggplot(h, aes(management, log10(biom+1), fill=FG)) + geom_boxplot()
#hist(h$biom[h$FG == 'Herbivore Scraper'])


h<- spread(h, FG, biom, fill=0)
colnames(h)[11:13]<-c('Herbivore Browser', 'Herbivore Grazer', 'Herbivore Scraper')
h<-as.data.frame(h)

#cor(h$hard.coral, h$complexity)
#cor(h$hard.coral, h$macroalgae)

```

```{r, echo=FALSE, include=TRUE, messages=FALSE, fig.cap='Correlation between explanatory covariates', fig.height=10, fig.width=10}
source('../../scripts/functions/plot-cor-functions.R')
pairs2(data.frame(h$hard.coral, h$macroalgae, h$complexity, h$management), 
       lower.panel=panel.smooth2, upper.panel = panel.cor)
```

```{r, echo=FALSE, include=FALSE, messages=FALSE}

##scale vars to keep covariate means = 0. helpful later.
h$hard.coral <- scale(h$hard.coral)
h$macroalgae <- scale(h$macroalgae)
h$complexity <- scale(h$complexity)

## make dummy variables
h$fish.dummy<-ifelse(h$management=='Fished', 1, 0)
h$pristine.dummy<-ifelse(h$management=='Unfished', 1, 0)
# we use 2 dummy variables for 3 levels

## convert biomass to log10
h$grazerlog10<-log10(h$'Herbivore Grazer'+1)
h$scraperlog10<-log10(h$'Herbivore Scraper' +1)
h$browserlog10<-log10(h$'Herbivore Browser'+1)

# testing model fit
m<-lmer(grazerlog10 ~ hard.coral + macroalgae + complexity + management + ## fixed
          (1 | dataset/reef) , ## random, nested = reefs within datasets
                data = h)
summary(m)
```





\newpage
### Grazers
&nbsp;

```{r, echo=FALSE, include=FALSE, messages=FALSE}
#### GRAZER BIOMASS MODELS

## drop 0 grazer site
h<-h[h$`Herbivore Grazer` > 0,]

m.grazer<-lmer(grazerlog10 ~ macroalgae + complexity + fish.dummy + pristine.dummy + ## fixed
          (1 | dataset/reef) , ## random, nested = reefs within datasets
                data = h)
summary(m.grazer)

```



```{r, echo=FALSE, include=TRUE, messages=FALSE, fig.cap='Grazer model residuals'}
## model diagnostic plots - grazer biomass
par(mfrow=c(2,2))
hist(resid(m.grazer))
hist(h$grazerlog10)
plot(resid(m.grazer), h$grazerlog10)
shapiro.test(resid(m.grazer)) #$ not great. it failed. but the eyeballs test is good.

```

```{r, echo=FALSE, include=TRUE, messages=FALSE, fig.cap='Grazer model effects'}

## NOW PLOT PREDICTIONS
grazer_nd_hc<-data.frame(hard.coral = seq(min(h$hard.coral), max(h$hard.coral), length.out=30),
                  macroalgae = 0, complexity = 0, fish.dummy = 0, pristine.dummy=0)

## predict grazer biomass for hard coral effect, holding every other covariate constant
p.grazer.hc<-predict(object=m.grazer, newdata = grazer_nd_hc, re.form=NA)

plot(grazer_nd_hc$hard.coral, p.grazer.hc, type='l',col=1, axes=F, ylab='Log10 Biomass (kg/ha)', xlab='Hard coral cover (%)', ylim=c(1, 4))
axis(1, at = seq(min(h$hard.coral), max(h$hard.coral), length.out=5), 
     labels= round(seq(min(pred$hard.coral), max(pred$hard.coral), length.out=5), 0))
axis(2)

par(xpd=T)
text(x=-0.5, y=1000, label='Hard coral effect', font=2)
legend('topright', legend=c('Grazer', 'Scraper', 'Browser'), col=c(1,2,3), lty=1)
```

#Now plot macroalgae for grazers

```{r, echo=FALSE, include=TRUE, messages=FALSE, fig.cap='Grazer model effects'}

## NOW PLOT PREDICTIONS
grazer_nd_m <-data.frame(macroalgae = seq(min(h$macroalgae), max(h$macroalgae), length.out=30),
                  hard.coral = 0, complexity = 0, fish.dummy = 0, pristine.dummy=0)

## predict grazer biomass for hard coral effect, holding every other covariate constant
p.grazer.m<-predict(object=m.grazer, newdata = grazer_nd_m, re.form=NA)

plot(grazer_nd_m$macroalgae, p.grazer.m, type='l',col=1, axes=F, ylab='Log10 Biomass (kg/ha)', xlab='Macroalgae cover (%)', ylim=c(1, 4))
axis(1, at = seq(min(h$macroalgae), max(h$macroalgae), length.out=5), 
     labels= round(seq(min(pred$macroalgae), max(pred$macroalgae), length.out=5), 0))
axis(2)

par(xpd=T)
text(x=-0.5, y=1000, label='Macroalgae effect', font=2)
legend('topright', legend=c('Grazer', 'Scraper', 'Browser'), col=c(1,2,3), lty=1)
```
#Plot 

\newpage
### Browsers
&nbsp;
```{r, echo=FALSE, include=FALSE, messages=FALSE}
#### BROWSER BIOMASS MODELS

## drop 0 grazer site
h<-h[h$`Herbivore Browser` > 0,]

m.browser<-lmer(browserlog10 ~ hard.coral + macroalgae * complexity + fish.dummy + pristine.dummy + ## fixed
          (1 | dataset/reef) , ## random, nested = reefs within datasets
                data = h)
summary(m.browser)

```

```{r}
## model diagnostic plots - browser biomass
par(mfrow=c(2,2))
hist(resid(m.browser))
hist(h$browserlog10)
plot(resid(m.browser), h$browserlog10)
shapiro.test(resid(m.browser)) #nope, but close enough again. We'll take what we can get. 

```



```{r, echo=FALSE, include=TRUE, messages=FALSE, fig.cap='Browser model effects'}

## NOW PLOT PREDICTIONS
browser_nd_hc <-data.frame(hard.coral = seq(min(h$hard.coral), max(h$hard.coral), length.out=30),
                  macroalgae = 0, complexity = 0, fish.dummy = 0, pristine.dummy=0)

## predict grazer biomass for hard coral effect, holding every other covariate constant
p.browser.hc<-predict(object=m.browser, newdata = browser_nd_hc, re.form=NA)

plot(browser_nd_hc$hard.coral, p.browser.hc, type='l',col=1, axes=F, ylab='Log10 Biomass (kg/ha)', xlab='Hard Coral Cover (%)', ylim=c(1, 4))
axis(1, at = seq(min(h$hard.coral), max(h$hard.coral), length.out=5), 
     labels= round(seq(min(pred$hard.coral), max(pred$hard.coral), length.out=5), 0))
axis(2)

par(xpd=T)
text(x=-0.5, y=1000, label='Hard coral effect', font=2)
legend('topright', legend=c('Grazer', 'Scraper', 'Browser'), col=c(1,2,3), lty=1)
```


